version: 2

updates:
  - package-ecosystem: "maven"
    directory: "."
    schedule:
      interval: "daily"
      time: "07:01"
      timezone: "Africa/Casablanca"

    open-pull-requests-limit: 5

    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"

    commit-message:
      prefix: "deps"
      include: "scope"

    reviewers:
      - "AsmaeTrb"
    assignees:
      - "AsmaeTrb"

    groups:
      spring:
        patterns:
          - "org.springframework*"
